// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVGG75Alfco6l9BSBTtsgY2yvrrtPjWEM',
    appId: '1:641177637479:web:53f30fabaa8c913bdf3ac2',
    messagingSenderId: '641177637479',
    projectId: 'fir-auth-ca9ce',
    authDomain: 'fir-auth-ca9ce.firebaseapp.com',
    storageBucket: 'fir-auth-ca9ce.appspot.com',
    measurementId: 'G-466VEMX9ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzXIwVMvX7JVQ9nLOMufSq1N11WdHXa0I',
    appId: '1:641177637479:android:4a607e92a65049b5df3ac2',
    messagingSenderId: '641177637479',
    projectId: 'fir-auth-ca9ce',
    storageBucket: 'fir-auth-ca9ce.appspot.com',
  );
}
